HR50/urls.py
from django.contrib import admin
from django.urls import include, path

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

urlpatterns = [
    path( '' , RedirectView . as_view ( url = 'apphr50/' )),
	path('apphr50/', include('apphr50.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # Авторизация
    path('accounts/', include('accounts.urls')), # Маршрут регистрации
    path('personalarea/', include('personalarea.urls')), # Маршрут регистрации 
	path('admin/', admin.site.urls),
]

accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views 
from .views import SignUpView
from accounts.views import home_view, signup_view, activation_sent_view, activation_sent_tl_view, activation_invalid_view, activate
from personalarea.views import prsar_view, grouphr_create, prsar_reggr_view, turn_on, turn_off
from django.contrib import admin
 
urlpatterns = [
	path('login/test_IDB/', views.test_IDB, name='test_IDB'),
    path('login/prsar/', prsar_view, name='prsar'),
    path('login/prsar_reggr/', prsar_reggr_view, name='prsar_reggr'),
    path('login/grouphr_create/', grouphr_create, name='grouphr_create'),
    path('', home_view, name="home"),
    path('signup/', signup_view, name="signup"),
	path('sent/', activation_sent_view, name="activation_sent"),
	path('sent/gm/', activation_sent_tl_view, name="activation_sent_tl"),	
	path('signup/', activation_invalid_view, name="activation_invalid"),	
	path('activate/<slug:uidb64>/<slug:token>/', activate, name="activate"),
]

accounts/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):

    SINGLE_USER = 'SU'
    GROUP_MEMBER = 'GM'
    TEAM_LEADER = 'TL'
    STATUS_OF_USER_CHOICES = [
        (SINGLE_USER, 'Одиночный пользователь'),
        (GROUP_MEMBER, 'Член группы'),
        (TEAM_LEADER, 'Руководитель группы'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150)
    status_of_user = models.CharField(max_length=50, choices=STATUS_OF_USER_CHOICES, default=SINGLE_USER, blank=True)
    data_of_registration = models.DateField(default=datetime.date.today())
    time_of_last_visit = models.DateTimeField(auto_now=True)
    signup_confirmation = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
		
    def is_upperclass(self):
        return self.status_of_user in {self.GROUP_MEMBER, self.TEAM_LEADER}

class Seanses(models.Model):

    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.CharField(max_length=100, blank=True)
    time_of_begin = models.DateTimeField(default=timezone.now())
    time_of_end = models.DateTimeField(auto_now=True)
    number_of_points_write = models.IntegerField(default=0)
    number_of_points_read = models.IntegerField(default=0)

    def __str__(self):
        return "Seanses of Users"
    
    @classmethod
    def create_seanse(cls, name_user, output_time_of_begin, number_of_points_write, number_of_points_read):
        seanse = cls(user = name_user, time_of_begin = output_time_of_begin, 
                    number_of_points_write = number_of_points_write, 
                    number_of_points_read = number_of_points_read)
        return seanse

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()
	
class Groupshr(models.Model):

    user = models.CharField(max_length=100, blank=True)
    name_of_grouphr = models.CharField(max_length=100, blank=True)
    time_of_registration = models.DateTimeField(default=timezone.now())
    comment_of_TL = models.CharField(max_length=1000, blank=True)
    operating_grouphr = models.BooleanField(default=False)
    #time_of_closing = models.DateTimeField(auto_now=True)
    #number_of_points_write = models.IntegerField(default=0)
    #number_of_points_read = models.IntegerField(default=0)

    def __str__(self):
        return "Groups of Users"
    
    @classmethod
    def create_grouphr(cls, name_user, name_of_grouphr, time_of_registration, comment_of_TL):
        grouphr = cls(user = name_user, name_of_grouphr = name_of_grouphr, 
                    time_of_registration = time_of_registration, 
                    comment_of_TL = comment_of_TL,
					operating_grouphr = True)
        return grouphr

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile, Seanses, Groupshr

#from models import Profile

class SignUpForm(UserCreationForm):
    
    SINGLE_USER = 'SU'
    GROUP_MEMBER = 'GM'
    TEAM_LEADER = 'TL'
    STATUS_OF_USER_CHOICES = [
        (SINGLE_USER, 'Одиночный пользователь'),
        (GROUP_MEMBER, 'Член группы'),
        (TEAM_LEADER, 'Руководитель группы'),
    ]	
    first_name = forms.CharField(max_length=100, label='Имя', help_text='Имя пользователя')
    last_name = forms.CharField(max_length=100, label='Фамилия', help_text='Фамилия пользователя')
    email = forms.EmailField(max_length=150, help_text='Email')
    status_of_user = forms.ChoiceField(choices=STATUS_OF_USER_CHOICES, 
	                                   label='Статус пользователя',
									   help_text='Статус пользователя')
    #name_of_group = forms.ChoiceField(label='Выбор группы',
	#								   help_text='Выберите группу в которой хотите зарегистрироваться')
    
	#choices_of_TL = []
    id_user = Profile.objects.filter(status_of_user=TEAM_LEADER).values_list('id', 'user')	# id всех руководителей групп
    #user_user = User.objects.filter(id=item).values_list('user')
    names_list = []
    i = 0
    for item in id_user:
		#id_user = User.objects.filter(username=item).values_list('id')
        user_user = User.objects.filter(id=id_user[i][1]).values_list('username')
        user_first_name = Profile.objects.filter(id=id_user[i][0]).values_list('first_name')
        user_last_name = Profile.objects.filter(id=id_user[i][0]).values_list('last_name')
        user_full_name = str(user_first_name[0][0]) + " " + str(user_last_name[0][0])	# полное имя руководителя групп
        #names_of_group_TL = Groupshr.objects.filter(id=id_user[i][0]).filter(operating_grouphr="True").values_list('name_of_grouphr')	# список работающих групп выбранного руководителя
        names_of_group_TL = Groupshr.objects.filter(user=user_user[0][0]).filter(operating_grouphr="True").values_list('name_of_grouphr')	# список работающих групп выбранного руководителя
        group_list = []
        #str_return = ''
        j = 0
        for item_group in names_of_group_TL:
            str_return = user_user[0][0] + ' ' + names_of_group_TL[j][0]
            #dict_return = {'name_TL':user_user[0][0], 'group_GM':names_of_group_TL[j][0]}
            group_list.append((str_return, names_of_group_TL[j][0]))
            j = j + 1
        #names_list.append((user_user[0][0], user_user[0][0]))
        #names_list.append((id_user[i][0], user_full_name))
        #names_list.append((item, id_user[i][0]))
        #names_list.append((item, user_first_name[0][0]))
        names_list.append((user_full_name, group_list))
        i = i + 1
	
    #self.fields['name_of_group'].choices = names_list
    name_of_group = forms.ChoiceField(choices=names_list,
	                                  label='Выбор группы', required=False)
									  #help_text='Выберите группу в которой хотите зарегистрироваться')
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
'email', 'password1', 'password2', 'status_of_user',)

class NumberOfPoints(forms.Form):
    #number_of_points = 1000
    number_of_points = forms.IntegerField(label = 'Количество точек тестовой последовательности:', min_value =1, max_value = 100) 

accounts/templates/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

accounts/templates/activation_request.html
{% autoescape off %}
Здравствуйте {{user}}.  Для активации своего аккаунта пройдите по этой ссылке:
<p><a href="http://{{ domain }}{% url 'activate' uidb64=uid token=token %}">Ссылка активации</a></p>
{% endautoescape %}

accounts/templates/activation_request_tl.html
{% autoescape off %}
Здравствуйте {{user}}.  Ваш аккаунт на сайте ЧСС активирован.
<p><a href="http://localhost:8000/apphr50/">Ссылка на сайт</a></p>
<!--
<p><a href="https://hr51.herokuapp.com/apphr50/">Ссылка на сайт</a></p>
-->
{% endautoescape %}

accounts/templates/activation_sent.html
<!--
<h3>На электронную почту выслана ссылка активации. Проверьте свой e-mail.</h3>
-->

<!-- templates/activation_sent.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}
 
{% block content %}
<div class="container">
	<div class="row">
		<div class="col">
			<div class="single-post">
				<h2 class="post-title"><a href="#"><?=$hdr?></a></h2>
				<p>Ссылка активации</p>
			</div>
		</div>
	</div>
</div>

<div class="container">
  <div class="row justify-content-around">
    <div class="card">
    <div class="card-body">
      <h5 class="card-title mb-2 text-muted">На электронную почту {{upe}} выслана ссылка активации. Проверьте свой e-mail. Для активации аккаунта перейдите по ссылке в Вашей электронной почте.</h5>
	</div>
    </div>	  
  </div>
</div>	  
{% endblock content %}

accounts/templates/activation_sent_tl.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
 
{% block content %}
<div class="container">
	<div class="row">
		<div class="col">
			<div class="single-post">
				<h2 class="post-title"><a href="#"><?=$hdr?></a></h2>
				<p>Ссылка активации</p>
			</div>
		</div>
	</div>
</div>

<div class="container">
  <div class="row justify-content-around">
    <div class="card">
    <div class="card-body">
      <h5 class="card-title mb-2 text-muted">На электронную почту администратора сайта выслана ссылка активации. После активации аккаунта администратором, Вам будет прислано подтверждение на Вашу электронную почту {{upe}}.</h5>
	</div>
    </div>	  
  </div>
</div>	  
{% endblock content %}

accounts/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=Inconsolata|Playfair+Display|Ubuntu:300" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	
	<link rel="stylesheet" href="css/style.css">

	<title>ЧСС</title>
</head>
<body>

	<header>
		<div class="container">
			<nav class="navbar navbar-expand-lg navbar-light">
				<a class="navbar-brand" href="#">ЧСС</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item"><a class="nav-link" href="{% url 'index' %}">На главную</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'about' %}">О чём сайт</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'whatfor' %}">Зачем нужен</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'howtouse' %}">Как пользоваться</a></li>
					</ul>
				</div>
			</nav>
		</div>
	</header>

	<div class="container">
		<div class="row">
			<div class="col">
				<div class="single-post">
				<!--
					<h3 class="post-category">Главная новость</h3>
				-->
					<h2 class="post-title"><a href="#"><?=$hdr?></a></h2>
					<p>Частота сердечных сокращений</p>
				</div>
			</div>
		</div>
	</div>	

    {% block content %}
    {% endblock %}

	<footer>
		<div class="container">
			<div class="d-sm-flex justify-content-between">
				<div class="footer-left">
					<p>
						Новосибирск 2021
					</p>
				</div>
			</div>
		</div>
	</footer>
	

<!--
	<script src="js/jquery-3.5.1.js"></script>
	<script src="js/popper.min.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<script src="js/main.js"></script>
-->
</body>
</html>

accounts/templates/home.html
<!-- templates/signup.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}
 
{% block content %}
<div class="container">
	<div class="row">
		<div class="col">
			<div class="single-post">
				<h2 class="post-title"><a href="#"><?=$hdr?></a></h2>
				<p>Активация аккаунта</p>
			</div>
		</div>
	</div>
</div>

<div class="container">
  <div class="row justify-content-around">
    <div class="card">
    <div class="card-body">
      <h5 class="card-title mb-2 text-muted">Поздравляем, Вы активировали зарегистрированный аккаунт {{user}}. Закройте эту страницу и зайдите на сайт под зарегистрированным аккаунтом.</h5>

	</div>
    </div>	  
  </div>
</div>	  
{% endblock content %}

accounts/templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}
 
{% block content %}
<div class="container">
	<div class="row">
		<div class="col">
			<div class="single-post">
				<h2 class="post-title"><a href="#"><?=$hdr?></a></h2>
				<p>Регистрация</p>
			</div>
		</div>
	</div>
</div>

<div class="container">
  <div class="row justify-content-around">
    <div class="card">
    <div class="card-body">
      <h5 class="card-title mb-2 text-muted">Введите Ваш аккаунт</h5>

<!--
      <form method="post">
      {% csrf_token %}
  
      <input type="hidden" name="next" value="{{ next }}">

      {{ form|crispy }}

      <button type="submit" class="btn btn-light">Зарегистрироваться</button>
 
      </form>
-->

      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button type="submit">Зарегистрироваться</button>
      </form>

		<script>
/*
		$(function () {	
		$('#js-button').click(function(){
			var value_t = $('#operations option:selected').text();
			var value_v = "0"; //$('#operations option:selected').val();
			$('#js-result').html('Выбрана операция: ' + value_t + '  ' + value_v);
			if (value_v == "0") {
				$("#new_group").show(); // зарегистрировать новую группу
			} else if (value_v == "1") {
				$("#turn_off_on_group").show(); // отключить/подключить старую группу
			} else if (value_v == "2") {
				$("#turn_off_on_user").show(); // отключить/подключить пользователя
			}
			});
		});
*/
		
		$(function () {	
		$('#id_status_of_user').click(function(){
			var value_t = $('#id_status_of_user option:selected').text();
			var value_v = $('#id_status_of_user option:selected').val();
			$('#js-result').html('Выбрана операция: ' + value_t + '  ' + value_v);
			if (value_v == "GM") {
				$("label[for='id_name_of_group']").show();
				$("#id_name_of_group").show();			
			} else if (value_v == "SU") {
				$("label[for='id_name_of_group']").hide();
				$("#id_name_of_group").hide();				
			} else if (value_v == "TL") {
				$("label[for='id_name_of_group']").hide();
				$("#id_name_of_group").hide();				
			}
			});
		});		
		
		$(function () {
			$(document).ready(function(){
			$("label[for='id_name_of_group']").hide();
			$("#id_name_of_group").hide();
			});
		}); 		
		</script>

	</div>
    </div>	  
  </div>
</div>	  
{% endblock content %}